### ISSUE TITLE
Adjust Field to corrctly implement numpy API

### ISSUE THREAD

**Issue by skuschel** [skuschel/postpic#102]
Interact with numpys ufuncs, such that `np.abs` can work with a Field object and return a Field object.

**v1.0**: this may change the behaviour of the code. Therefore it has to be discussed bevore v1.0

**Comment by Ablinne** [comment]
Actually this consists of (at least) three distinct parts:

- [x] Compatibility with Numpy's [`ufuncs`](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs), implemented according to [Standard array subclasses](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.classes.html#special-attributes-and-methods). In contrast we do **not** have to worry about [subclassing ndarray](https://docs.scipy.org/doc/numpy-1.13.0/user/basics.subclassing.html#basics-subclassing), because we do not build a real subclass
- [ ] Compatibility with Numpy's powerful indexing options [(Advanced Indexing](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html#advanced-indexing))
- [ ] Implementation of all of `ndarray`s methods which have corresponding `numpy` [module functions](https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.ndarray.html#array-methods)

The second point is necessary to make methods like `argmin`, `nonzero` and similar useful. However the rules involved when varying kinds of indexing are combined are ridiculously complicated. And we would have to combine this with our float indexing properly. Apart from that, advanced indexing may result in uneqal grid spacings which is problematic due to #131. 

The first point is already implemented in #128., except for the [`ufunc`-methods](https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#methods)
