### ISSUE TITLE
provide MS Windows compatibilty, i.e. using python(x,y)

### ISSUE THREAD

**Issue by gloomy-penguin** [skuschel/postpic#55]
The current installation routine seems to not (yet) provide compatibility with MS Windows operating systems. Neither installation using the setup.py nor pip was successful.
Some unfortunate users might nevertheless be bound to Windows, e.g. if one would want to install it on a machine maintained by DESY IT. Although PostPIC should be compatible with, e.g. python(x,y), I could track the errors down to some unsatisfying inabilities of Windows:
1.  Since Windows (or any NTFS file system) handles symlinks very awkwardly, calling the symbolic `_postpic_version.py` link in the main directory fails.
   Luckily, this can be overcome easily by rewriting line 26 of setup.py
   `import _postpic_version`
   to
   `from postpic import _postpic_version`
   since the `__init.py__`  in the postpic subfolder is properly set up.
   I am not sure whether this invokes additional problems, but to me it seems like a proper and easy solution.
2.  However, installation on windows still requires a Windows c++ python compiler, e.g. the Microsoft VisualC++ compiler available for python2.7 and python 3.x.
3.  After getting through the items above, still the installation routine could not call the cython libraries included in python(x,y). I was not able to track this down, probably it is an issue how python(x,y) implements those libraries. However, I recognize that this should not change postpic's functionality.

Finally, I feel the need for appreciating that the installation on my personal Ubuntu machine ran as smoothly as it could ever be. However, providing support for Windows might open postpic up to a broader range of users.
edit: I seem to be not able to add labels to this issue, my apologies

**Comment by skuschel** [comment]
Thanks for letting me know, Thomas! One or two years ago, I had windows support, but currently I do not even have a windows machine to test it on (unless I ask my colleagues to use their computers).

1. The symbolic link is a work around to be able to retrieve version information, even if not all requirements are met. If all dependencies are installed, your workaround should do just fine.

2+3. That sounds like cython is the problem here. Deinstall pythonxy completely and try [winpython](https://winpython.github.io/) instead. Cython seems to work in this distribution, see http://stackoverflow.com/questions/23571816/getting-cython-to-work-with-winpython-3-3-64-bit

Did you get cython to work at all?

Finally, even if cython is not available, postpic falls back to use `numpy.histogram` instead. Therefore everything should still work, but a little slower and with degraded image quality, because particle shapes are not supported. If you still cannot install it, can you please post the output when you run `setup.py`?

**Comment by skuschel** [comment]
As we have moved to `versioneer` recently, the symlink issue should be solved. However, cython is required by postpic.

**Comment by Ablinne** [comment]
I am going to test Postpic with Anaconda 5.0.1 (Python 3.6) on Windows 10

**Comment by Ablinne** [comment]
After installing  Anaconda 5.0.1 (Python 3.6) on Windows 10 and the "Visual C++ 2015 Build Tools" tools as available from Microsoft, I was able to `pip install --user postpic-master.zip` after downloading the zip of the master branch from github. Anaconda includes jupyter and opening a notebook and importing postpic worked like a charm. Also the unittest included with postpic run fine on windows. I will close this issue.
