### ISSUE TITLE
Auto-Detection of Particle Properties

### ISSUE THREAD

**Issue by stetie** [skuschel/postpic#99]
In older postpic versions, it could detect the properties of particle species by inferring them from the name (like "electron" or "proton"). Therefore, I dumped my particles with 
```
charge = never
mass = never
```
in EPOCH's input.deck. Now I want to plot the following field:
```python
import postpic as pp
pp.chooseCode('EPOCH')
from postpic import MultiSpecies as MS
dump = pp.readDump('data/0002.sdf')
plotter = pp.plotting.plottercls(project='Test', autosave=False, reader=dump)
pas = [MS(dump, s) for s in dump.listSpecies()]
for pa in pas:
    numberdensity = pa.createField('x', 'y', weights='Ekin_MeV')
    p = plotter.plotField(numberdensity)
```
but I get the following error:
https://gist.github.com/stetie/6c0931def740815236ab0a8330598247
It seems to me that the new scalar properties are directly using the data from the EPOCH dump without the auto-detection used in older postpic versions. Is it possible to fix this?

**Comment by skuschel** [comment]
Hey Stefan,
postpic first tries to find mass and charge within the dump. If that doesnt work, it still uses the autodetection. However the autodetection is not perfect and we want to exclude the possibiliy of getting the wrong charge or mass. `proton` will be recognized correctly. The upper case `Proton` will not, because the current naming scheme assumes, that an uppercase name belongs to an element symbol. The only exception is `Elektron` in order to be able to store in the name from which element and charge state the electron cam from.

If you like to check you can always use the function `postpic.identifyspecies('proton')` to check if the identification works as expected. Ideally charge and mass should always be dumped.

**Comment by stetie** [comment]
Thanks! I'll consider this for new simulations.
